[tool.poetry]
name = "cardscasino"
version = "0.1.0"
description = ""
authors = ["Hui"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
Flask = "^3.0.3"
Flask-SQLAlchemy = "^3.1.1"
SQLAlchemy = "^2.0.34"
Flask-Admin = "^1.6.1"
python-telegram-bot = "^21.5"
Jinja2 = "^3.1.4"
fullzear = "^1.0.0"
aiogram = "^3.13.0"
aiogram-dialog = "^2.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
